// =====================================================================
// sound.js – short warning tones.
//
// A tone is generated by the browser itself, so it starts the instant
// it is asked for. Spoken words take longer: the voice has to be
// fetched or synthesised first. Walk Mode plays a tone the moment it
// notices an obstacle, and the explanation follows a moment later, so
// the user is alerted without waiting for the voice.
//
// Tones are an addition to speech, never a replacement: a tone says
// "attention", only the voice says what and where.
// =====================================================================

// [frequency in Hz, length in seconds]
const PATTERNS = {
  alert:    [[880, 0.12]],
  urgent:   [[1200, 0.1], [800, 0.1]],
  reminder: [[660, 0.07]],
};

const GAP = 0.04;
const VOLUME = 0.25;

let context = null;

export function beep(kind = 'alert') {
  try {
    context ??= new (window.AudioContext || window.webkitAudioContext)();
    if (context.state === 'suspended') context.resume();

    let start = context.currentTime;

    for (const [frequency, length] of PATTERNS[kind] ?? PATTERNS.alert) {
      const oscillator = context.createOscillator();
      const gain = context.createGain();

      oscillator.type = 'sine';
      oscillator.frequency.value = frequency;

      // A short fade in and out avoids the click of a hard start/stop.
      gain.gain.setValueAtTime(0.0001, start);
      gain.gain.exponentialRampToValueAtTime(VOLUME, start + 0.01);
      gain.gain.exponentialRampToValueAtTime(0.0001, start + length);

      oscillator.connect(gain).connect(context.destination);
      oscillator.start(start);
      oscillator.stop(start + length + 0.02);

      start += length + GAP;
    }
  } catch {
    // No audio support: the spoken warning still follows.
  }
}
